import { ReactNode } from "react"
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server"
import { ThemeProvider } from "next-themes";
import Navbar from "@/src/components/Navbar";
import FooterSec from "@/src/components/FooterSec";
import ChangeTheme from "@/src/ui/ChangeTheme";
import LocaleSwitcher from "@/src/components/LocaleSwitcher";
import "@/src/style/globals.css";

type Props = {
  children: ReactNode,
  params: { locale: string }
}

export const metadata: Metadata = {
  title: "Amil's portfolio",
  description: "This website generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Props) {


  const messages = await getMessages()

  return (
    <html lang={locale} suppressHydrationWarning >



      <body>
        <ThemeProvider attribute="class">
          <NextIntlClientProvider messages={messages}>

            <ChangeTheme /> <LocaleSwitcher locale={locale} />
            <header>
              <div className=" w-full text-black dark:bg-black dark:text-white">
                <Navbar />
              </div>
            </header>

            {children}
            <footer className=" flex  flex-wrap text-black dark:bg-black dark:text-white items-center justify-center">
              <FooterSec />
            </footer>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

